# Generated by Django 3.1.3 on 2020-11-28 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', default='', max_length=50)),
                ('surname', models.CharField(blank='False', default='', max_length=50)),
                ('role', models.CharField(blank='False', default='', max_length=50)),
                ('number', models.CharField(blank='False', default='', max_length=50)),
                ('date', models.DateField(default='')),
                ('optional_number', models.CharField(blank='False', default='', max_length=50)),
                ('address', models.CharField(blank='False', default='', max_length=50)),
                ('reason', models.CharField(blank='False', default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
