# Generated by Django 3.1.3 on 2020-11-29 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201128_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='address',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='new',
            name='number',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='new',
            name='optional_number',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='new',
            name='reason',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='new',
            name='role',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='surname',
            field=models.CharField(blank='True', default='', max_length=50),
        ),
    ]
