# Generated by Django 3.1.3 on 2020-11-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201129_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.BooleanField(default='False'),
        ),
    ]
