# Generated by Django 3.1.3 on 2020-12-01 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20201129_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='address',
            field=models.CharField(blank='False', default='', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(blank='False', default='', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='number',
            field=models.CharField(blank='False', default='', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='optional_number',
            field=models.CharField(blank='False', default='', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='reason',
            field=models.CharField(blank='False', default='', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='role',
            field=models.CharField(blank='False', default='', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.BooleanField(default='False', null='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='surname',
            field=models.CharField(blank='False', default='', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='new',
            name='user',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
