# Generated by Django 3.1.3 on 2020-12-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201201_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='status',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default='False', null='True')),
                ('new', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='users.new')),
            ],
        ),
    ]
