# Generated by Django 3.1.3 on 2020-12-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_status_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='remark',
            field=models.CharField(default='', max_length=50),
        ),
    ]
