# Generated by Django 3.1.3 on 2021-01-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0004_auto_20210109_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content',
        ),
    ]
