# Generated by Django 2.2.17 on 2021-01-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0007_auto_20210122_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(related_name='comments', to='boss.Post'),
        ),
    ]
