# Generated by Django 2.2.17 on 2021-01-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0009_auto_20210122_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='post',
        ),
    ]
